spring.application.name=rideshare

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ride_share_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Qwerasd123@}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# Google OAuth2
google.client.id=${GOOGLE_CLIENT_ID:919641654832-19kufjo7k3co5e12c45isu77dlhmti57.apps.googleusercontent.com}